services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app/public:/var/www/html
            - ./configurations/php.ini:/usr/local/etc/php/php.ini
            - ./configurations/apache2.conf:/etc/apache2/apache2.conf
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-db_root_password}
            MYSQL_USER: ${MYSQL_USER:-db_user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-db_password}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-db_template}
        ports:
            - "${LOCAL_PORT}:80"
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-db_root_password}
            MYSQL_USER: ${MYSQL_USER:-db_user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-db_password}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-db_template}
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 38060:3306
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8051:80
        environment:
            - PMA_ARBITRARY=1
        depends_on:
            - mysql
volumes:
    mysqldata: {}
